# Generated by Django 3.2.6 on 2021-08-26 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_projectscreenshot_priority_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='priority_order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
