# Generated by Django 3.2.6 on 2021-09-13 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_category_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='source_code',
            field=models.URLField(blank=True),
        ),
    ]
