# Generated by Django 3.2.6 on 2021-10-29 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_alter_project_source_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='screenshots',
        ),
        migrations.AddField(
            model_name='screenshot',
            name='priority_order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='screenshot',
            name='project',
            field=models.ForeignKey(
                default='',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='screenshots',
                to='portfolio.project',
            ),
        ),
        migrations.DeleteModel(
            name='ProjectScreenshot',
        ),
    ]
