# Generated by Django 3.2.6 on 2021-11-01 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_auto_20211029_1303'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['priority_order']},
        ),
        migrations.AlterModelOptions(
            name='screenshot',
            options={'ordering': ['priority_order']},
        ),
        migrations.AlterField(
            model_name='screenshot',
            name='project',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='screenshots', to='portfolio.project'),
        ),
    ]
