# Generated by Django 3.2.6 on 2022-03-25 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_category_priority_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='thumbnail',
        ),
    ]
