# Generated by Django 3.2.6 on 2022-04-02 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_auto_20220402_0547'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
    ]
