# Generated by Django 3.2.6 on 2022-07-05 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_auto_20220628_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenshot',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='screenshots', to='portfolio.project'),
        ),
    ]
